### ISSUE TITLE
rake aborted

### ISSUE THREAD

**Issue by mictadlo** [wurmlab/flo#19]
Hi,
I ran into the following problem:

```
…
Processing mito11
mkdir run/test_v2
liftOver -gff /work/team/banana/assembly/bam2consensus/flo/test_v2.gff3 run/liftover.chn run/test_v2/lifted.gff3 run/test_v2/unlifted.gff3
Reading liftover chains
Mapping coordinates
WARNING: -gff is not recommended.
Use 'ldHgGene -out=<file.gp>' and then 'liftOver -genePred <file.gp>'
/lustre/work-lustre/team/apps/flo/gff_recover.rb run/test_v2/lifted.gff3 2> unprocessed.gff | gt gff3 -tidy -sort -addids -retainids - > run/test_v2/lifted_cleaned.gff
warning: GFF3 file "-" is empty
warning: GFF3 file "-" is empty
warning: GFF3 file "-" is empty
ln -s /work/team/banana/assembly/bam2consensus/flo/test_v2.gff3 run/test_v2/input.gff
/lustre/work-lustre/team/apps/flo/gff_compare.rb cds run/source.fa run/target.fa run/test_v2/input.gff run/test_v2/lifted_cleaned.gff > run/test_v2/unmapped.txt
gt gff3 -sort -retainids run/test_v2/input.gff | gt extractfeat -type CDS -join -retainids -seqfile run/source.fa -matchdescstart - > run/test_v2/input.cds.fa
gt gff3: error: illegal GFF version pragma in line 46728 of file "run/test_v2/input.gff": ##gff-version 3 (merge multiple GFF3 files with `gt gff3 -sort` and do not concatenate them manually)
gt extractfeat: error: GFF3 file "-" is empty
/lustre/work-lustre/team/miniconda2/envs/flo/lib/ruby/2.2.0/rake/file_utils.rb:66:in `block in create_shell_runner': Command failed with status (1): [gt gff3 -sort -retainids run/musa_acuminat...] (RuntimeError)
	from /lustre/work-lustre/team/miniconda2/envs/flo/lib/ruby/2.2.0/rake/file_utils.rb:57:in `call'
	from /lustre/work-lustre/team/miniconda2/envs/flo/lib/ruby/2.2.0/rake/file_utils.rb:57:in `sh'
	from /lustre/work-lustre/team/miniconda2/envs/flo/lib/ruby/2.2.0/rake/file_utils_ext.rb:37:in `sh'
	from /lustre/work-lustre/team/apps/flo/gff_compare.rb:25:in `extract_cds'
	from /lustre/work-lustre/team/apps/flo/gff_compare.rb:46:in `<main>'
rake aborted!
Command failed with status (1): [/lustre/work-lustre/team/apps/f...]
/work/team/apps/flo/Rakefile:56:in `block (2 levels) in <top (required)>'
/work/team/apps/flo/Rakefile:40:in `each'
/work/team/apps/flo/Rakefile:40:in `block in <top (required)>'
Tasks: TOP => default
(See full trace by running task with --trace)
```

How could I fix the gff3 file?

Best wishes,

Michal

**Comment by yeban** [comment]
Empty output is generated when input annotations are not in GFF3 format or 1st column of the GFF file does not match chromsome, scaffold, or contig ids in the source assembly. flo now informs user of the same if liftOver's output is empty.
